### ISSUE TITLE
Error: grounded MRF object is too memory consumptive?

### ISSUE THREAD

**Issue by tinicode** [opcode81/ProbCog#23]
I created an MLN model based on the YAGO dataset and tried to run grounding and inference with ProbCog. But it stopped while running grounding and output 'Killed: 9'. My laptop also displayed a pop-up saying that the system has no more program memory available. 
But is it possible that running the example attached consumes the total memory capacity? I run the example on a Macbook with 8GB RAM. Does ProbCog has an implemented work-around in order to save partial grounding results on disk? Many thanks for your help!

<img width="241" alt="image" src="https://user-images.githubusercontent.com/43300855/62009004-0de81f80-b15a-11e9-9f87-a41d6af2d7f5.png"> <img width="271" alt="image" src="https://user-images.githubusercontent.com/43300855/62009008-19d3e180-b15a-11e9-831c-631590d383d3.png">

[yago_example.zip](https://github.com/opcode81/ProbCog/files/3439282/yago_example.zip)

**Comment by opcode81** [comment]
I don't see how you could run into grounding issues, because both your MLN and your database are invalid. The very first formula of your MLN binds the same variable ('a') to two different domains ('something' and 'person'): isKnownFor(b, a) ^ isMarriedTo(b, a) => isMarriedTo(a, b)
'a' cannot simultaneously be a person and something somebody is known for.
Also, your evidence database contains strings with characters that are not admissible for constants.
