### ISSUE TITLE
ProbCog vs NetKit-srl

### ISSUE THREAD

**Issue by amirj** [opcode81/ProbCog#4]
Hi,
I just interested to know the pros and cons of ProbCog in comparison to [NetKit-srl](http://netkit-srl.sourceforge.net).
Specially I'm interested to know if statistical relational models (and also these tools) are scalable to large data graph?

**Comment by opcode81** [comment]
I am not familiar with NetKit-srl. Therefore I cannot compare it to ProbCog.

Regarding scalability, the answer is "It depends":
- How large is large? ProbCog will only work on networks and datasets that will fit in memory. So if "large" is not larger than the memory of your 64bit system, then it could be manageable.
- How complex/demanding are your models? In the general case, probabilistic inference (and therefore also learning, which includes inference as a sub-problem) is #P-hard. Therefore, unless your model is within a subclass of models for which highly efficient methods exist or (crude) approximations are sufficient for your application, size is not your only problem. For instance, if the graph is a polytree or its potentials completely lack determinism, then you will typically be able to handle much larger problems than you would otherwise.
